Support for setting a profile by a client MAC address. This assumes that a simulator machine/VM is also used as a DHCP server (IP address resolved from DHCP_LEASES file). No master-slave code check is performed in this case.

diff --git a/www/cgi-bin/set b/www/cgi-bin/set
--- a/www/cgi-bin/set
+++ b/www/cgi-bin/set
@@ -48,9 +48,20 @@ EOF
 		exit
 	fi
 	UPDATEIP=${PATHS[2]}
+elif valid_mac "${PATHS[2]}"
+then
+    DHCPIP=$(get_leased_ip_from_mac "${PATHS[2]}")
+    if ! valid_ip "$DHCPIP"
+    then
+		cat <<EOF
+{"status": 0, "error": "no dhcp lease entry for a given mac address"}
+EOF
+		exit
+    fi
+	UPDATEIP=$DHCPIP 
 else
 	cat <<EOF
-{"status": 0, "error": "invalid ip address"}
+{"status": 0, "error": "invalid ip or mac address"}
 EOF
 	exit
 fi
